CXX := g++
CXX_FLAGS := -std=c++11 -O2 -fpermissive -g

BIN := bin
INCLUDE := include
SRC := src

folders = utils exp exp/operator tensor nn data
all_header_files  = $(foreach folder, $(folders), $(wildcard $(INCLUDE)/$(folder)/*.hpp))
all_src_files     = $(foreach folder, $(folders), $(wildcard $(SRC)/$(folder)/*.cpp))
all_src_basenames = $(basename $(notdir $(all_src_files)))
all_objects       = $(addprefix $(BIN)/, $(addsuffix .o, $(all_src_basenames)))

.PHONY : test train_mlp train_cnn clean

test: $(BIN)/test.exe
	@echo build test finished

train_mlp: $(BIN)/train_mlp.exe
	@echo build train_mlp finished

train_cnn: $(BIN)/train_cnn.exe
	@echo build train_cnn finished

$(BIN)/test.exe: $(BIN)/test.o $(all_objects)
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -o $@ $^

$(BIN)/test.o: test.cpp $(all_header_files)
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $@ $< 

$(BIN)/train_mlp.exe: $(BIN)/train_mlp.o $(all_objects)
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -o $@ $^

$(BIN)/train_mlp.o: train_mlp.cpp $(all_header_files)
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $@ $< 

$(BIN)/train_cnn.exe: $(BIN)/train_cnn.o $(all_objects)
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -o $@ $^

$(BIN)/train_cnn.o: train_cnn.cpp $(all_header_files)
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $@ $< 

clean:
	rm $(BIN)/*.o
	rm $(BIN)/*.exe

# The following content is automatically generated by update_makefile.py


$(BIN)/data.o: src/data/data.cpp include/data/data.hpp include/utils/base_config.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/data.o src/data/data.cpp

$(BIN)/init.o: src/nn/init.cpp include/nn/init.hpp include/utils/exception.hpp \
 include/tensor/tensor.hpp include/exp/exp.hpp include/exp/exp_impl.hpp \
 include/utils/allocator.hpp include/utils/base_config.hpp \
 include/utils/array.hpp include/exp/grad_impl.hpp \
 include/exp/operator/log_softmax.hpp include/exp/operator/constant.hpp \
 include/exp/operator/reduce_op.hpp include/exp/operator/nll_loss.hpp \
 include/exp/operator/conv.hpp include/exp/operator/basic_op.hpp \
 include/tensor/tensor_impl.hpp include/tensor/storage.hpp \
 include/tensor/shape.hpp include/tensor/grad_meta.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/init.o src/nn/init.cpp

$(BIN)/module.o: src/nn/module.cpp include/exp/function.hpp \
 include/utils/allocator.hpp include/utils/base_config.hpp \
 include/utils/exception.hpp include/exp/exp_impl.hpp include/utils/array.hpp \
 include/exp/grad_impl.hpp include/exp/operator/log_softmax.hpp \
 include/exp/operator/constant.hpp include/exp/operator/reduce_op.hpp \
 include/exp/operator/nll_loss.hpp include/exp/operator/conv.hpp \
 include/exp/exp.hpp include/exp/operator/basic_op.hpp \
 include/exp/operator/matrix_op.hpp include/nn/module.hpp \
 include/tensor/tensor.hpp include/tensor/tensor_impl.hpp \
 include/tensor/storage.hpp include/tensor/shape.hpp \
 include/tensor/grad_meta.hpp include/nn/init.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/module.o src/nn/module.cpp

$(BIN)/optim.o: src/nn/optim.cpp include/tensor/storage.hpp \
 include/utils/base_config.hpp include/utils/allocator.hpp \
 include/tensor/tensor.hpp include/exp/exp.hpp include/exp/exp_impl.hpp \
 include/utils/array.hpp include/exp/grad_impl.hpp include/utils/exception.hpp \
 include/exp/operator/log_softmax.hpp include/exp/operator/constant.hpp \
 include/exp/operator/reduce_op.hpp include/exp/operator/nll_loss.hpp \
 include/exp/operator/conv.hpp include/exp/operator/basic_op.hpp \
 include/tensor/tensor_impl.hpp include/tensor/shape.hpp \
 include/tensor/grad_meta.hpp include/nn/optim.hpp include/nn/module.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/optim.o src/nn/optim.cpp

$(BIN)/shape.o: src/tensor/shape.cpp include/tensor/shape.hpp \
 include/utils/base_config.hpp include/utils/allocator.hpp \
 include/utils/array.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/shape.o src/tensor/shape.cpp

$(BIN)/storage.o: src/tensor/storage.cpp include/tensor/storage.hpp \
 include/utils/base_config.hpp include/utils/allocator.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/storage.o src/tensor/storage.cpp

$(BIN)/tensor.o: src/tensor/tensor.cpp include/tensor/tensor.hpp include/exp/exp.hpp \
 include/exp/exp_impl.hpp include/utils/allocator.hpp \
 include/utils/base_config.hpp include/utils/array.hpp \
 include/exp/grad_impl.hpp include/utils/exception.hpp \
 include/exp/operator/log_softmax.hpp include/exp/operator/constant.hpp \
 include/exp/operator/reduce_op.hpp include/exp/operator/nll_loss.hpp \
 include/exp/operator/conv.hpp include/exp/operator/basic_op.hpp \
 include/tensor/tensor_impl.hpp include/tensor/storage.hpp \
 include/tensor/shape.hpp include/tensor/grad_meta.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/tensor.o src/tensor/tensor.cpp

$(BIN)/tensor_impl.o: src/tensor/tensor_impl.cpp include/tensor/tensor_impl.hpp \
 include/exp/exp_impl.hpp include/utils/allocator.hpp \
 include/utils/base_config.hpp include/utils/array.hpp \
 include/exp/grad_impl.hpp include/utils/exception.hpp \
 include/exp/operator/log_softmax.hpp include/exp/operator/constant.hpp \
 include/exp/operator/reduce_op.hpp include/exp/operator/nll_loss.hpp \
 include/exp/operator/conv.hpp include/tensor/storage.hpp \
 include/tensor/shape.hpp include/tensor/grad_meta.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/tensor_impl.o src/tensor/tensor_impl.cpp

$(BIN)/allocator.o: src/utils/allocator.cpp include/utils/allocator.hpp \
 include/utils/base_config.hpp include/utils/exception.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/allocator.o src/utils/allocator.cpp

$(BIN)/exception.o: src/utils/exception.cpp include/utils/exception.hpp
	$(CXX) $(CXX_FLAGS) -I $(INCLUDE) -c -o $(BIN)/exception.o src/utils/exception.cpp

